name: rnn_anomaly
channels:
  - defaults
dependencies:
  - python=3.7.5
  - requests
  - matplotlib
  - scikit-learn
  - numpy
  - pandas
  - tqdm
  - pip:
    - azureml-sdk
    - torch
    - torchvision
    - mlflow
